name: audioschool
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  audio_session: ^0.1.11
  rxdart: ^0.27.7
  just_audio_mpv: ^0.1.6
  just_audio_windows: ^0.2.0
  
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.1.0

#FireBase
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0
  flutter_svg: ^1.1.4
  just_audio: ^0.9.30



flutter:
  assets:
  - images/
  - assets/


  uses-material-design: true

 